### ISSUE TITLE
ResourceWarning: unclosed file in reader.py

### ISSUE THREAD

**Issue by jonatasrs** [suds-community/suds#63] opened 2021-12-07 18:51 UTC
This warning is showing when run whith `python -Wa`

python3.7/site-packages/suds/reader.py:72: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/suds/suds-***-document.px'>

**Comment by jonatasrs** [comment] 2021-12-07 21:12
I was investigating the problem, and found it to be a conflict if you have both `suds-jurko` and `suds-community` installed. Then `suds-jurko` should automatically be removed when installing `suds-community`.

**Comment by phillbaker** [comment] 2021-12-12 19:50
Hi @jonatasrs, thanks for opening the issue. We'll have to investigate the reported warning. Did it include a longer stracktrace that you can share?

Regarding the package conflict, setuptools doesn't have a way to specify conflicts that I'm aware of, so specifying conflicting packages isn't possible today.

**Comment by phillbaker** [comment] 2021-12-30 02:01
Hello - can you please include a reproduction for this and include the version of suds that you're using? I'm not able to reproduce this.

**Comment by phillbaker** [comment] 2021-12-31 15:57
I'm going to close this issue out as a dupe of https://github.com/suds-community/suds/pull/28.

Looking at the code, the last time that the line number you're referencing didn't point to a comment was back in the 0.6 release: https://github.com/suds-community/suds/blob/release-0.6/suds/reader.py#L72. Since this has been fixed in more recent versions, please update.

**Closed by phillbaker** 2021-12-31 15:57 UTC
Labels: bug

**Comment by jonatasrs** [comment] 2022-01-18 20:52
Yes, the problem is that suds-jurko is not automatically removed when installing suds-community. I am manually removing suds-jurko before installing suds-community. 
I saw that now "suds-communty" is "suds" so I already adjusted it in my code, https://pypi.org/project/suds/ 
Thanks for the answer.
