### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by hiteshgoyal18** [suds-community/suds#46] opened 2020-12-11 09:34 UTC
It was working fine till yesterday. 
Nothing changed. same network, same code but no solution till now. Any help would be highly appreciated
```
Traceback (most recent call last):
  File "/opt/wwts/opt/dashboard/dashboard/wmp_sockets.py", line 5, in <module>
    from dashboard import app
  File "/opt/wwts/opt/dashboard/dashboard/__init__.py", line 73, in <module>
    from .work_order.views import blueprint as work_order_views  # noqa
  File "/opt/wwts/opt/dashboard/dashboard/work_order/views.py", line 96, in <module>
    from dashboard.work_order.service import CallCertificationsService
  File "/opt/wwts/opt/dashboard/dashboard/work_order/service.py", line 17, in <module>
    _gtcd = GTCallData()
  File "/opt/wwts/opt/dashboard/dashboard/wwits_apis/soap.py", line 159, in __init__
    super(WwitsClient, self).__init__(
  File "/opt/wwts/lib/python3.8/site-packages/suds/client.py", line 120, in __init__
    self.wsdl = reader.open(url)
  File "/opt/wwts/lib/python3.8/site-packages/suds/reader.py", line 104, in open
    wsdl = self.fn(url, self.options)
  File "/opt/wwts/lib/python3.8/site-packages/suds/wsdl.py", line 190, in __init__
    self.build_schema()
  File "/opt/wwts/lib/python3.8/site-packages/suds/wsdl.py", line 252, in build_schema
    self.schema = container.load(self.options, loaded_schemata)
  File "/opt/wwts/lib/python3.8/site-packages/suds/xsd/schema.py", line 102, in load
    child.open_imports(options, loaded_schemata)
  File "/opt/wwts/lib/python3.8/site-packages/suds/xsd/schema.py", line 351, in open_imports
    imported = imp.open(options, loaded_schemata)
  File "/opt/wwts/lib/python3.8/site-packages/suds/xsd/sxbasic.py", line 578, in open
    self.__download(url, loaded_schemata, options))
  File "/opt/wwts/lib/python3.8/site-packages/suds/xsd/sxbasic.py", line 591, in __download
    d = reader.open(url)
  File "/opt/wwts/lib/python3.8/site-packages/suds/reader.py", line 148, in open
    xml = self.__fetch(url)
  File "/opt/wwts/lib/python3.8/site-packages/suds/reader.py", line 189, in __fetch
    fp = self.options.transport.open(request)
  File "/opt/wwts/lib/python3.8/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/opt/wwts/lib/python3.8/site-packages/suds/transport/http.py", line 67, in open
    return self.u2open(u2request)
  File "/opt/wwts/lib/python3.8/site-packages/suds/transport/http.py", line 128, in u2open
    return url.open(u2request, timeout=tm)
  File "/opt/wwts/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/wwts/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/wwts/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/wwts/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/wwts/lib/python3.8/urllib/request.py", line 1354, in do_open
    r = h.getresponse()
  File "/opt/wwts/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/opt/wwts/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/opt/wwts/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/wwts/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
```

**Comment by phillbaker** [comment] 2021-01-18 21:00
Hi @hiteshgoyal18 can you provide a reproducible test case? 

As well, the following should be provided:
* suds version
* copies or links to the WSDL being used

At a glance, this seems like a network error and not a bug in the client Suds library.

**Comment by phillbaker** [comment] 2021-01-23 22:21
I'm going to close this for now, please re-open if you have further details.

**Closed by phillbaker** 2021-01-23 22:21 UTC
