### ISSUE TITLE
Headers passed into suds.client.Client() are not used in WSDL and XSD requests

### ISSUE THREAD

**Issue by chris-griffin** [suds-community/suds#27] opened 2019-08-27 20:05 UTC
`suds.client.Client()` allows you to pass in custom HTTP headers to be used in the requests to the SOAP webservice

For example: 

```py
suds.client.Client(url, headers={'Host': '127.0.0.1')
```

This will correctly set the Host HTTP header for SOAP operation requests. However, it will not correctly set the Host HTTP for the initial WSDL and subsequent XSD requests.

This can be problematic if the webservice requires a specific HTTP header for all requests (including the initial WSDL load).

It looks like this is where we would need to add the headers for the WSDL request

https://github.com/suds-community/suds/blob/c94298c87dd6675330d660ba6a1fd56265e03c48/suds/reader.py#L165-L196

And here for the subsequent XSD requests

https://github.com/suds-community/suds/blob/c94298c87dd6675330d660ba6a1fd56265e03c48/suds/xsd/sxbasic.py#L587-L598

**Comment by ovnicraft** [comment] 2019-11-20 16:12
So PR #12 solve this ?

**Comment by phillbaker** [comment] 2019-11-21 03:14
#12 solved #11, which was about passing headers when making service requests. This issue is about request the WSDLs, which happens prior to making service requests and uses a separate code path.

**Comment by rmarzocchi84** [comment] 2019-12-13 06:52
I need to use the http header to access o the soap service .
I try with 

`
from suds.client import *
WSDL_URL = 'xxxxxx'
client = Client(WSDL_URL, headers={'Authorization': 'xxxxxxx'})
`
but I encountered this strange error:

`
File "test_ws.py", line 46, in <module>
    client = Client(WSDL_URL, headers={'Authorization': 'xxxxxxx'})
  File "/usr/local/lib/python3.6/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/usr/local/lib/python3.6/site-packages/suds/reader.py", line 151, in open
    d = self.fn(url, self.options)
  File "/usr/local/lib/python3.6/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/usr/local/lib/python3.6/site-packages/suds/reader.py", line 78, in open
    d = self.download(url)
  File "/usr/local/lib/python3.6/site-packages/suds/reader.py", line 94, in download
    fp = self.options.transport.open(Request(url))
  File "/usr/local/lib/python3.6/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/usr/local/lib/python3.6/site-packages/suds/transport/http.py", line 69, in open
    raise TransportError(str(e), e.code, e.fp)
suds.transport.TransportError: HTTP Error 405: Method Not Allowed
`

**Comment by phillbaker** [comment] 2019-12-13 14:28
@rmarzocchi84 [a HTTP 405](https://httpstatuses.com/405) is not typically returned for invalid authentication. Have you tried to access the WSDL URL using `curl` and passing the appropriate headers?

**Comment by rmarzocchi84** [comment] 2019-12-16 17:36
I try with

```
curl --header "'Authorization': 'Bearer XXXX'"  url_address
```

but I have the same 405 error

**Comment by rmarzocchi84** [comment] 2019-12-18 07:32
Effectively if I try with SoapUI without HTTP header I obtain a different error:


```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault>
         <faultcode xmlns:axis2ns1322341="http://schemas.xmlsoap.org/soap/envelope/">axis2ns1322341:Client</faultcode>
         <faultstring>Authentication Failure</faultstring>
         <detail>Required OAuth credentials not provided</detail>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by rmarzocchi84** [comment] 2019-12-19 13:28
Perhaps the problem is related to this issue https://stackoverflow.com/questions/47951270/python-3-http-error-405-method-not-allowed

**Comment by phillbaker** [comment] 2019-12-21 16:52
Fixed in https://github.com/suds-community/suds/commit/654c1950596223d1278eafa9e7b2e52ae13ded13. Being released as 0.8.4.

@rmarzocchi84 please note, this may not fix your issue - it seems like the API you're working with is very particular. If you can provide a working example of accessing the API using any client, then perhaps we can debug using it with suds.

@chris-griffin please note the addition to the README and the example in the test in that commit. Headers for transport options passed to the `Client` constructor are only used if the default transport is used. So if `transport` is a keyword arg passed to `Client`, then headers, should be specified as options on the transport object directly, e.g.:
```
t = SpecialTransport()
t.options.headers = {'foo': 'bar'} # since we create a custom client, options must be set explicitly
suds.client.Client('http://example.com/', transport=t)
```
This may also apply to proxy, timeout,  username, password, however, I didn't verify that.

**Closed by phillbaker** 2019-12-21 16:53 UTC

**Comment by rmarzocchi84** [comment] 2019-12-23 08:54
@phillbaker the problem is that the API I try to use is not my.. and I can only access to it using a VPN so it is really difficult for me to provide an example

a strange behaviour of the API with problems do not expose methods, while the original WS which correctly works with suds (without using API)  expose methods

**Comment by rmarzocchi84** [comment] 2020-01-29 07:17
Using requests it works: 

```
import os,sys,re #,shutil,glob
import requests
import token_api_ge as t
import xml.etree.ElementTree as et
from xml.etree.ElementTree import parse

def get_response_from_provider(token, IdSegnalante, Descrizione, IdManufatto, CodViaDa, CivicoDa,  ColoreDa, LetteraDa):
    url = t.url
    #print(url)
    headers = {'Authorization': 'Bearer {}'.format(token),
               'content-type': 'text/xml'}
    #headers = {'Authorization': 'Bearer {}'.format(token)}
    #headers = {'content-type': 'text/xml'}
    body1 = """
    <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:goad="http://goadev.com/">
   <soap:Header/>
   <soap:Body>
      <goad:InserimentoSegnalazione>
         <!--Optional:-->
         <goad:manutenzioneSegnalazioneInput>
            <goad:IdTipologiaSegnalazione>7</goad:IdTipologiaSegnalazione>
            <goad:IdModalitaSegnalazione>6</goad:IdModalitaSegnalazione>
            <goad:IdSegnalante>{}</goad:IdSegnalante>
            <goad:IdManufatto>{}</goad:IdManufatto>
            <!--Optional:-->
            <goad:Descrizione>{}</goad:Descrizione>
            <goad:IdTipologiaIntervento>21</goad:IdTipologiaIntervento>
            <!--Optional:-->
            <goad:Matricola>emergenze</goad:Matricola>
            <goad:CodViaDa>{}</goad:CodViaDa>
            <!--Optional:-->
            <goad:CivicoDa>{}</goad:CivicoDa>
            <!--Optional:-->
            <goad:ColoreDa>{}</goad:ColoreDa>
            <!--Optional:-->
            <!--goad:LetteraDa>{}</goad:LetteraDa-->
         </goad:manutenzioneSegnalazioneInput>
         <!--Optional:-->
         <goad:autenticazione>
            <!--Optional:-->
            <goad:Software>test</goad:Software>
            <!--Optional:-->
            <goad:User>test</goad:User>
            <!--Optional:-->
            <goad:Password>test</goad:Password>
         </goad:autenticazione>
      </goad:InserimentoSegnalazione>
   </soap:Body>
</soap:Envelope>
    """.format(IdSegnalante,IdManufatto,Descrizione,CodViaDa,CivicoDa,ColoreDa, LetteraDa)
    response = requests.post(url, data=body1, headers=headers)
    #print("Info recieved...")
    #print(response.content)
    root = et.fromstring(response.content)
    #print('####################################################')
    id_segnalazione=root[0][0][0][1].text
    #id_segn = elem.attrib['IdSegnalazione']
    #print(id_segn)
    return response, id_segnalazione
```
